FROM golang:1.21-alpine AS builder
WORKDIR /app
COPY go.mod .
COPY main.go .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags "-w -s" -o order-service .

FROM scratch
COPY --from=builder /app/order-service /order-service
EXPOSE 3003
CMD ["/order-service"]
